import { describe, it } from "node:test";
import assert from "node:assert/strict";
import {
  computeGeneratedFileHash,
  assertGeneratedClientIntegrity,
  HandEditedGeneratedFileError,
} from "./client-generator.ts";

describe("Client generation integrity", () => {
  it("verifies intact generated client source", () => {
    const code = "/* GENERATED BY UNIERP - DO NOT EDIT */\nexport class UniErpClient {}";
    const hash = computeGeneratedFileHash(code);

    const res = assertGeneratedClientIntegrity("sdk/client.ts", code, hash);
    assert.equal(res.verified, true);
  });

  it("throws HandEditedGeneratedFileError on hand-edited code modification", () => {
    const originalCode = "/* GENERATED BY UNIERP - DO NOT EDIT */\nexport class UniErpClient {}";
    const originalHash = computeGeneratedFileHash(originalCode);
    const handEditedCode = "/* GENERATED BY UNIERP - DO NOT EDIT */\nexport class UniErpClient { /* custom hack */ }";

    assert.throws(
      () => assertGeneratedClientIntegrity("sdk/client.ts", handEditedCode, originalHash),
      (err: any) => {
        return err instanceof HandEditedGeneratedFileError && err.actualHash !== originalHash;
      }
    );
  });
});
