import { describe, it } from "node:test";
import assert from "node:assert/strict";
import {
  computeGeneratedFileHash,
  assertGeneratedClientIntegrity,
  HandEditedGeneratedFileError,
  assertDartDifferentialParity,
  DartContractDivergenceError,
} from "./client-generator.ts";

describe("Client generation integrity", () => {
  it("verifies intact generated client source", () => {
    const code = "/* GENERATED BY UNIERP - DO NOT EDIT */\nexport class UniErpClient {}";
    const hash = computeGeneratedFileHash(code);

    const res = assertGeneratedClientIntegrity("sdk/client.ts", code, hash);
    assert.equal(res.verified, true);
  });

  it("throws HandEditedGeneratedFileError on hand-edited code modification", () => {
    const originalCode = "/* GENERATED BY UNIERP - DO NOT EDIT */\nexport class UniErpClient {}";
    const originalHash = computeGeneratedFileHash(originalCode);
    const handEditedCode = "/* GENERATED BY UNIERP - DO NOT EDIT */\nexport class UniErpClient { /* custom hack */ }";

    assert.throws(
      () => assertGeneratedClientIntegrity("sdk/client.ts", handEditedCode, originalHash),
      (err: any) => {
        return err instanceof HandEditedGeneratedFileError && err.actualHash !== originalHash;
      }
    );
  });

  it("asserts parity between canonical TypeScript contracts and Dart client definitions", () => {
    const canonicalFields = ["id", "tenantId", "status", "createdAt", "updatedAt"];
    const dartGeneratedFields = ["id", "tenantId", "status", "createdAt", "updatedAt"];

    const res = assertDartDifferentialParity("OrderContract", canonicalFields, dartGeneratedFields);
    assert.equal(res.verified, true);
  });

  it("throws DartContractDivergenceError when Dart generation misses canonical fields", () => {
    const canonicalFields = ["id", "tenantId", "status", "createdAt", "updatedAt"];
    const incompleteDartFields = ["id", "tenantId", "status"]; // missing createdAt, updatedAt

    assert.throws(
      () => assertDartDifferentialParity("OrderContract", canonicalFields, incompleteDartFields),
      (err: any) => {
        return (
          err instanceof DartContractDivergenceError &&
          err.contractId === "OrderContract" &&
          err.missingInDart.includes("createdAt")
        );
      }
    );
  });
});
